# common configuration
include:
exclude:
kill:
defaultBrowser:

# api server configuration
server:
  port:
  secret:

# tistory
tistory:
  rthi:
    id:
    pw:
    client_id:
    client_secret:
    redirect_uri:
  today_log:
    id:
    pw:
    client_id:
    client_secret:
    redirect_uri:

# telegram
telegram:
  telegramBotToken:
  telegramChannels:
  telegramId:

# google
google:
  id:
  pw:
  api_key:
  client_id:
  client_secret:
  redirect_url:

youtube:
  api_key:
