# common configuration
process_kill_regexp:

# api server configuration
server:
  port:
  secret:

# tistory
tistory:
  rthi:
    domain:
    id:
    pw:
    client_id:
    client_secret:
    redirect_uri:
  almondbongbong:
    domain:
    id:
    pw:
    client_id:
    client_secret:
    redirect_uri:
    seleniumProtocol:
    seleniumHost:
    seleniumPort:

# telegram
telegram:
  telegramBotToken:
  telegramChannels:
  telegramId:

# google
google:
  id:
  pw:
  api_key:
  client_id:
  client_secret:
  redirect_url: