# api server configuration
server:
  port:
  secret:

# tistory
tistory:
  rthi:
    domain:
    id:
    pw:
  almondbongbong:
    domain:
    id:
    pw:
    seleniumProtocol:
    seleniumHost:
    seleniumPort:

# telegram
telegram:
  telegramBotToken:
  telegramChannels:
  telegramId:
