# common configuration
process_kill_regexp:

# api server configuration
server:
  port:
  secret:

# tistory
tistory:
  rthi:
    id:
    pw:
    client_id:
    client_secret:
    redirect_uri:
  almondbongbong:
    id:
    pw:
    client_id:
    client_secret:
    redirect_uri:
  mygumi:
    id:
    pw:
    client_id:
    client_secret:
    redirect_uri:
  ahribori2:
    id:
    pw:
    client_id:
    client_secret:
    redirect_uri:
  discover_new_music:
    id:
    pw:
    client_id:
    client_secret:
    redirect_uri:


# telegram
telegram:
  telegramBotToken:
  telegramChannels:
  telegramId:

# google
google:
  id:
  pw:
  api_key:
  client_id:
  client_secret:
  redirect_url:

youtube:
  api_key: 